[package]
name = "deeptrade_core"
version = "1.0.0"
edition = "2024.beta"

[dependencies]
# Mainnet version
deepbook = { local = "../deepbook", address = "0xcaf6ba059d539a97646d47f0b9ddf843e138d215e2a12ca1f4585d386f7aec3a" }
Pyth = { local = "../pyth", address = "0x04e20ddf36af412a4096f9014f4a565af9e812db9a05cc40254846cf6ed0ad91" }
multisig = { git = "https://github.com/DeeptradeProtocol/multisig-move.git", subdir = "move", rev = "main" }

[addresses]
deeptrade_core = "0x0"
